on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: An Action to Collect Community Vote
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stackk Community Governance Check
        uses: ./test-action/
        id: hello
        with:
          who-to-greet: "Stackk"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
